### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by herohamp** [wwwwwwwwwwwwwwwwwwwwwwwwwwwwww/kahoot.js#2]
class Kahoot extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/.kahoot/node_modules/kahoot.js/index.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by wwwwwwwwwwwwwwwwwwwwwwwwwwwwww** [comment]
Please read the README before opening an issue. You are using an old version of node.js.
